name: Update on PR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

  workflow_dispatch:
      inputs:
        ENVIRONMENT:
          description: 'environment name'
          required: true
          default: 'sandbox'

        AWS_REGION:
          description: 'aws region'
          required: true
          default: 'us-east-1'

jobs:

  update-script:
    runs-on: ubuntu-latest
    env:
      environement : ${{ github.event.inputs.ENVIRONMENT }}
      aws_region : ${{ github.event.inputs.AWS_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: demo job
        run: echo "changes made and PR raised for ${{env.environement}}-${{env.aws_region}}


  see-working-dir:
    runs-on: ubuntu-latest
    steps:
      - name : checkout code
        uses : actions/checkout@v2
      - name : checking dir
        run : pwd 
