name: Update index.html on PR

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: demo job
        run: echo "changes made and PR raised"