name: Update on PR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  workflow_dispatch:
      inputs:
        ENVIRONMENT:
          description: 'Pass the environment name'
          required: true
          default: "sandbox"
          type: environment
        AWS_REGION:
          description: 'Pass the aws region'
          required: true
          default: "us-east-1"
jobs:
  update-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: demo job
        run: echo "changes made and PR raised on env - ${{ inputs.ENVIRONMENT }} - $ {{ inputs.AWS_REGION }}"

  see-working-dir:
    runs-on: ubuntu-latest
    needs: update-script
    steps:
      - name : checkout code
        uses : action/checkout@v2
      - name : checking dir
        run : pwd 


