name: Update on PR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened

  workflow_dispatch:
      inputs:
        ENVIRONMENT:
          description: 'environment name'
          default: 'sandbox'
          type : environment
        AWS_REGION:
          description: 'aws region'
          default: 'us-east-1'
          type : string

jobs:

  echo-env_and_region:
    runs-on: ubuntu-latest
    env:
      environement : ${{ inputs.ENVIRONMENT || 'sandbox' }}
      aws_region : ${{ inputs.AWS_REGION || 'us-east-1' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: demo job
        run: echo "changes made and PR raised for ${{env.environement}}-${{env.aws_region}}"


  see-working-dir:
    runs-on: ubuntu-latest
    needs: echo-env_and_region
    steps:
      - name : checkout code
        uses : actions/checkout@v2
      - name : checking dir
        run : pwd 
