name: Update on PR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  workflow_dispatch:
      inputs:
        ENVIRONMENT:
          description: 'Pass the environment name'
          required: true
          default: "sandbox"
          type: environment
        AWS_REGION:
          description: 'Pass the aws region'
          required: true
          default: "us-east-1"
jobs:
  update-index:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: demo job
        run: echo "changes made and PR raised on env - ${{ inputs.ENVIRONMENT }} - $ {{ inputs.AWS_REGION }}"
